export const ADD_FEED = 'ADD_FEED';
export const ADD_FEED_FAIL = 'ADD_FEED_FAIL';
export const ADD_FEED_SUCCESS = 'ADD_FEED_SUCCESS';

export const ADD_FEED_COMMENT = 'ADD_FEED_COMMENT';
export const ADD_FEED_COMMENT_FAIL = 'ADD_FEED_COMMENT_FAIL';
export const ADD_FEED_COMMENT_SUCCESS = 'ADD_FEED_COMMENT_SUCCESS';

export const REMOVE_FEED = 'REMOVE_FEED';
export const REMOVE_FEED_FAIL = 'REMOVE_FEED_FAIL';
export const REMOVE_FEED_SUCCESS = 'REMOVE_FEED_SUCCESS';
