export const WEATHER_GET = 'WEATHER_GET';
export const WEATHER_GET_SUCCESS = 'WEATHER_GET_SUCCESS';
export const WEATHER_GET_FAIL = 'WEATHER_GET_FAIL';

export const AIR_QUALITY_GET = 'AIR_QUALITY_GET';
export const AIR_QUALITY_GET_SUCCESS = 'AIR_QUALITY_GET_SUCCESS';
export const AIR_QUALITY_GET_FAIL = 'AIR_QUALITY_GET_FAIL';

export const SELECT_CITY = 'SELECT_CITY';

export const WEATHER_DATA_GET = 'WEATHER_DATA_GET';
export const WEATHER_DATA_GET_SUCCESS = 'WEATHER_DATA_GET_SUCCESS';
export const WEATHER_DATA_GET_FAIL = 'WEATHER_DATA_GET_FAIL';
